server {
    listen 80;
    server_name ribeboys.ac.ke www.ribeboys.ac.ke;

    location / {
        proxy_pass http://public_website:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api {
        proxy_pass http://server:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name portal.ribeboys.ac.ke;

    location / {
        proxy_pass http://dashboard:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
